### PR TITLE
Fixing extension logging

### LINKED ISSUE #874: openwpm.log full of this type of error from `resource://openwpm/privileged/stackDump/OpenWPMStackDumpChild.jsm`
## Configuration:
Newly clone and install.
Tag: v0.14.0
Set number of browser: 10

## Problem 
`openwpm.log` is full of the error message below during running demo.py (with a site list): 
```
2021-03-23 15:01:09,284 - MainProcess[log-interceptor-515602707]- selenium_firefox     - DEBUG   : BROWSER 515602707: driver: JavaScript error: resource://openwpm/privileged/stackDump/OpenWPMStackDumpChild.jsm, line 119: InvalidStateError: JSWindowActorChild.contentWindow getter: Cannot access property 'contentWindow' after actor 'OpenWPMStackDump' has been destroyed
```
Here is an example of the log file: (Please scrawl down to about 600th rows to see what's happening)
[openwpm.log](https://1drv.ms/u/s!AtYIZf-S9U-igao8Jp3B-rzl5M-Dxw?e=73RMha)

Although it seems that the crawl process is alright in the end, and I can manually filter out this message, I'm still worried that:
1. What does this message mean? Is it ok to see them while crawling?
2. What could be the problem? I tried reinstall openwpm, which can't fix that.

Thank you!

### LINKED ISSUE #906: Connection error NS_ERROR_UNEXPECTED
I am trying to run web extension and connect it to the remote server to receive the data. But once the browser starts it can not establish connection to the remote socket server. Code throws this error:

`Exception { name: "NS_ERROR_UNEXPECTED", message: "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIBinaryOutputStream.writeByteArray]", result: 2147549183, filename: "file:///home/shashi/python/OpenWPM/openwpm/Extension/firefox/src/privileged/sockets/api.js", lineNumber: 154, columnNumber: 0, data: null, stack: "sendData@file:///home/shashi/python/OpenWPM/openwpm/Extension/firefox/src/privileged/sockets/api.js:154:34\nrecvAPICall/result</<@resource://gre/modules/ExtensionParent.jsm:956:68\nwithPendingBrowser@resource://gre/modules/ExtensionParent.jsm:489:26\nrecvAPICall/result<@resource://gre/modules/ExtensionParent.jsm:956:24\ncallAndLog@resource://gre/modules/ExtensionParent.jsm:918:14\nrecvAPICall@resource://gre/modules/ExtensionParent.jsm:955:25\n", location: XPCWrappedNative_NoHelper }`

screenshot-nimbus-capture-2021 04 28-19_42_49

And while debugging I found that the issue is in create transport layer code which is as follows(**api.js**, **line no**: 129):

`var transport = socketService.createTransport([], host, port, null);`

However, the the official documentation has this explanation of the function:
```
createTransport(in Array<ACString> aSocketTypes,
                                      in AUTF8String aHost,
                                      in long aPort,
                                      in nsIProxyInfo aProxyInfo,
                                      in nsIDNSRecord dnsRecord);
```
_Reference(https://searchfox.org/mozilla-central/source/netwerk/base/nsISocketTransportService.idl#58)_

So changing the function call worked for me.
`var transport = socketService.createTransport([], host, port, null, null);`

### PR DESCRIPTION
**Pull request by vringar**
This is a follow-up to #911
Fixes #906

### CODE REVIEW

File: openwpm/Extension/firefox/feature.js/index.js [hunk 1]
```diff
@@ -53,6 +53,10 @@ async function main() {
                        config['logger_address'],
                        config['browser_id']);
 
+  if (config["extra"]["pre_instrumentation_code"]) {
+    eval(config["extra"]["pre_instrumentation_code"])
+
```
Comment (englehardt) [inline openwpm/Extension/firefox/feature.js/index.js]:
```suggestion
```

**Review by englehardt — APPROVED** [review]

**Comment by vringar** [comment]
Any changes to the StackDumpChildActor break the tests, so I'm willing to accept the errors in the logs for now.
